global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'expense-service'
    static_configs:
      - targets: ['expense-service:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
